### PR TITLE
Tests for CR fixes

### PR DESCRIPTION
**Pull request by olydis**
awaiting client runtime 2.3.11

### CODE REVIEW

**Comment by olydis** [comment]
# publish job
~~~ Haskell
> waiting for PR to get merged or closed
~~~

**Comment by olydis** [comment]
# publish job
~~~ Haskell
> waiting for PR to get merged or closed
~~~

**Comment by olydis** [comment]
# AutoRest automatic publish job
~~~ Haskell
> will publish once/if PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by azuresdkci1x** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by azuresdkci1x** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by azuresdkci1x** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by azuresdkci1x** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by azuresdkci1x** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by azuresdkci1x** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by azuresdkci1x** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by azuresdkci1x** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by azuresdkci1x** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by azuresdkci1x** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by azuresdkci1x** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 96%

<details><summary>19 out of 535 features are not covered by tests</summary><p>

[`additionalPropertiesInProperties`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInProperties), [`additionalPropertiesInPropertiesWithAPTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInPropertiesWithAPTypeString), [`additionalPropertiesTrue`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTrue), [`additionalPropertiesTypeObject`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeObject), [`additionalPropertiesTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeString), [`animalNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=animalNotFoundError), [`expectedNoErrors`](https://github.com/Azure/autorest.testserver/search?q=expectedNoErrors), [`expectedPetHungryError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetHungryError), [`expectedPetSadError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetSadError), [`getComplexPolymorphicRecursiveValid`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphicRecursiveValid), [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated), [`intError`](https://github.com/Azure/autorest.testserver/search?q=intError), [`linkNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=linkNotFoundError), [`putComplexPolymorphicRecursiveValid`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphicRecursiveValid), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putComplexPolymorphismNoDiscriminator`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismNoDiscriminator), [`putComplexPolymorphismValid`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismValid), [`putComplexReadOnlyPropertyValid`](https://github.com/Azure/autorest.testserver/search?q=putComplexReadOnlyPropertyValid), [`stringError`](https://github.com/Azure/autorest.testserver/search?q=stringError)</p></details>

## ❌️ Azure: 0%

no tests were run for this category

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 96%

<details><summary>19 out of 535 features are not covered by tests</summary><p>

[`additionalPropertiesInProperties`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInProperties), [`additionalPropertiesInPropertiesWithAPTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInPropertiesWithAPTypeString), [`additionalPropertiesTrue`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTrue), [`additionalPropertiesTypeObject`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeObject), [`additionalPropertiesTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeString), [`animalNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=animalNotFoundError), [`expectedNoErrors`](https://github.com/Azure/autorest.testserver/search?q=expectedNoErrors), [`expectedPetHungryError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetHungryError), [`expectedPetSadError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetSadError), [`getComplexPolymorphicRecursiveValid`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphicRecursiveValid), [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated), [`intError`](https://github.com/Azure/autorest.testserver/search?q=intError), [`linkNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=linkNotFoundError), [`putComplexPolymorphicRecursiveValid`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphicRecursiveValid), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putComplexPolymorphismNoDiscriminator`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismNoDiscriminator), [`putComplexPolymorphismValid`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismValid), [`putComplexReadOnlyPropertyValid`](https://github.com/Azure/autorest.testserver/search?q=putComplexReadOnlyPropertyValid), [`stringError`](https://github.com/Azure/autorest.testserver/search?q=stringError)</p></details>

## ✔️ Azure: 100%

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.3*

## ❌️ General: 97%

<details><summary>12 out of 535 features are not covered by tests</summary><p>

[`additionalPropertiesInProperties`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInProperties), [`additionalPropertiesInPropertiesWithAPTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInPropertiesWithAPTypeString), [`additionalPropertiesTrue`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTrue), [`additionalPropertiesTypeObject`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeObject), [`additionalPropertiesTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeString), [`animalNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=animalNotFoundError), [`expectedNoErrors`](https://github.com/Azure/autorest.testserver/search?q=expectedNoErrors), [`expectedPetHungryError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetHungryError), [`expectedPetSadError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetSadError), [`intError`](https://github.com/Azure/autorest.testserver/search?q=intError), [`linkNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=linkNotFoundError), [`stringError`](https://github.com/Azure/autorest.testserver/search?q=stringError)</p></details>

## ✔️ Azure: 100%

**Pull request merged**
