### PR TITLE
Upgrade `@autorest/modelerfour` to `4.15.442`

### PR DESCRIPTION
**Pull request by amrElroumy**
Upgrading `@autorest/modelerfour` to `4.15.442` to address this issue https://github.com/Azure/autorest/issues/3630

### CODE REVIEW

**Comment by amrElroumy** [comment]
@pakrym we need to upgrade `@autorest/modelerfour` to `4.15.442`, can you help me in understanding why the CI build is failing?

In the build logs, I see there are description values that were missing and been added, if I understand it properly:
image

**Comment by pakrym** [comment]
CI has a check that all generated code is up to date, it includes the autorest code model files that you see.

Can you please run `.\eng\Generate.ps1` and check-in all the produced changes?

**Comment by amrElroumy** [comment]
> CI has a check that all generated code is up to date, it includes the autorest code model files that you see.
> 
> Can you please run `.\eng\Generate.ps1` and check-in all the produced changes?

Thanks for the tip @pakrym .

I'm having trouble with `GetDictionaryDictionaryItemNull`, I'm unsure how I should fix that one, can you help?

**Comment by pakrym** [comment]
I've disabled it for now. Id requires a testserver update that is slightly more involved.

**Review by pakrym — APPROVED** [review]

**Pull request merged**
