### PR TITLE
Catch exceptions and report as fatal instead

### PR DESCRIPTION
**Pull request by chamons**
- It is very common to comment out 4 lines in CSharpGen.cs when
  debugging a crash, as we won't generate yaml needed to debug in VS
  if we throw an exception during code generation.
- By catching everything, and using autorest.Fatal() we still fail
  builds, but also complete the yaml write out above

### CODE REVIEW

**Review by pakrym — APPROVED** [review]

**Review by ShivangiReja — APPROVED** [review]

**Comment by pakrym** [comment]
Are you sure this works? I've seen exceptions being reported as FATAL already.

**Comment by pakrym** [comment]
https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/AutoRest/Plugins/PluginProcessor.cs#L41

**Comment by chamons** [comment]
I did the trivial test of:
- Delete entire Generated folder of a sample
-  .\eng\Generate.ps1 on a case where I knew it crashed
- 
image

So I _think_ it does?

**Comment by pakrym** [comment]
Ah you are still returning `true` from the generator. It might cause autorest not to fail with the correct error code.

**Comment by chamons** [comment]
I added a `return false` and I'm still seeing the same write yaml out behavior.

**Comment by pakrym** [comment]
I'm fine trying this change but it seems to be equivalent to the code we already hav.e

**Comment by chamons** [comment]
:shrug: - I'm not sure why it works, just that it does. I've tested before and after multiple times, and it is consistent.

I can do more digging if you'd like, I figured I'd just try it after our meeting and was surprised that it worked.

**Comment by pakrym** [comment]
Up to you. I'm fine merging or doing more investigation.

**Pull request merged**
