### PR TITLE
fix the class name for cref element to include full namespace

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Fixes https://github.com/Azure/autorest.csharp/issues/3744

# Description

Previously, in some cases when our generator wants to write a type into `cref`, it will not write its full name.
The discriminator extra descriptions have this issue. The comment there is written like:
```csharp
/// please note that <see cref="Foo"/> is the base class
```
This comment is in the class of `Foo` as well as the entry for `Foo` class in the model factory.

It is OK to have this in the `Foo` class file, but it is actually incorrect in the model factory because `cref` is actually pointing to the method `Foo` defined in the model factory.

A worse case happens when our model factory must have customization to mitigate a breaking change. When this happens, we have two methods with `Foo` as their names (they are overloads to each other), but the cref now will not compile any more, because the compiler is complaining the ambiguity.

This PR changes the type of `description` in multiple places from `string` to `FormattableString`, so that the type information could be properly stored in the `FormattableString` and handled eventually and correctly by `CodeWriter`. Otherwise despite the description is built from a formattable string, it evaluates its value and invokes the `ToString` method on CSharpType which has issues of new lines etc.

In the changes this PR made, we always write full name in crefs, such as
```
/// Please <see cref="global::NamespaceOfFoo.Foo"/>
```
and let Roslyn to trim off whatever it assumes necessary to trim off. There might be some additional namespace added in the test projects and regen, but since Roslyn thinks it is necessary to keep, it is OK to keep them - they do not really harm anything anyway.

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

### CODE REVIEW

**Review by ArthurMa1978 — APPROVED** [review]

**Comment by live1206** [comment]
Should we handle the Description in [MethodSignature](https://github.com/Azure/autorest.csharp/blob/712159bdc66d48d01a6bb7b5302df3600f964b79/src/AutoRest.CSharp/Common/Output/Models/MethodSignature.cs#L15C75-L15C86) as well? It could be types with same name in different namespaces.

**Comment by ArcturusZhang** [comment]
> Should we handle the Description in [MethodSignature](https://github.com/Azure/autorest.csharp/blob/712159bdc66d48d01a6bb7b5302df3600f964b79/src/AutoRest.CSharp/Common/Output/Models/MethodSignature.cs#L15C75-L15C86) as well? It could be types with same name in different namespaces.

I will update that as well.

**Comment by ArcturusZhang** [comment]
> Should we handle the Description in [MethodSignature](https://github.com/Azure/autorest.csharp/blob/712159bdc66d48d01a6bb7b5302df3600f964b79/src/AutoRest.CSharp/Common/Output/Models/MethodSignature.cs#L15C75-L15C86) as well? It could be types with same name in different namespaces.

well I tried to update the methodsignature.Summary and description property to FormattableString, and finding more of similar cases.
This might make this PR big and out of its initial purpose.
I will create an issue to track this possible refactor item.

**Comment by live1206** [comment]
> > Should we handle the Description in [MethodSignature](https://github.com/Azure/autorest.csharp/blob/712159bdc66d48d01a6bb7b5302df3600f964b79/src/AutoRest.CSharp/Common/Output/Models/MethodSignature.cs#L15C75-L15C86) as well? It could be types with same name in different namespaces.
> 
> well I tried to update the methodsignature.Summary and description property to FormattableString, and finding more of similar cases. This might make this PR big and out of its initial purpose. I created an issue to track this possible refactor item: #3750

I was expecting more similar cases, we can limit this PR to just fix it for parameter.

**Pull request merged**
