### PR TITLE
Merge Errorhandling into master

### PR DESCRIPTION
**Pull request by sorenlorentzen**
Can we get this merged? We really need the exception handling.

### CODE REVIEW

**Comment by mortenmoulder** [comment]
Would love this as well.

**Comment by zitcomdev** [comment]
> Would love this as well.

+1

**Comment by daniel-white** [comment]
let's get this out! can someone pull the branch and fix the conflicts?

**Comment by Keschke** [comment]
Are there any updates?
This functionality would be very helpful!

**Comment by MiYanni** [comment]
For now, closing PRs for v2 changes. If there is business justification for this PR, we can reopen.

**Comment by JoostvdB94** [comment]
As documentation describes [here](http://azure.github.io/autorest/extensions/#x-ms-error-response), i expected this as a feature already in place for autorest generators.

Business case:
For completeness we want to include status codes as BadRequest, Forbidden and Unauthorized in our API spec (as possible and expected response codes). 

However, Autorest will ignore these error codes when they are specified in the spec leading to silent errors (empty response). 

Marking response codes as error will combine completeness of the api schema, and improve error handling for clients.

Please reopen this PR and merge.

**Comment by MiYanni** [comment]
@JoostvdB94 Currently, we aren't accepting PRs for the v2 generator. We've been hard at work on the v3 generator, which works with Azure.Core. Errors would be handled through the Azure.Core pipeline. In v3, currently all x-ms-error-responses will result in operation failures appropriately.

**Pull request closed without merging**
