### PR TITLE
change things depending on my own properties in lowlevelclients into lazy loading pattern

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Regen: No change

# Description

Properties inside LowLevelClient are initialized in its ctor, but while initializing some of them, it is using the properties of the same instance. When the ctor does not end, the properties will be null, this disables us to debug the class.

This PR defers the calculation to happen on their first invocation.

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
> Approved but can we double check this gets rid of the debug race condition I demoed?

I tried to debug through the code about building constructors and it is working fine, no exception was thrown.

**Comment by m-nash** [comment]
> > Approved but can we double check this gets rid of the debug race condition I demoed?
> 
> I tried to debug through the code about building constructors and it is working fine, no exception was thrown.

Were you able to repro the issue before you changes to verify this fixes it?  If not let me know since i can repro before I can download this branch and validate it doesn't happen anymore.

**Comment by m-nash** [comment]
I don't see the repro any longer.

**Comment by lirenhe** [comment]
@ArcturusZhang,   for "Regen: generating... (no changes in SDK expected)",  was the regen completed?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang, for "Regen: generating... (no changes in SDK expected)", was the regen completed?

Yes and no change

**Review by lirenhe — APPROVED** [review]

**Pull request merged**
