### PR TITLE
Fix lro test

### PR DESCRIPTION
**Pull request by shahabhijeet**
Fix for LRO tests.
Updating ClientRuntime.Azure version.
This PR depends upon publishing changes for AutoRest.TestServer PR
https://github.com/Azure/autorest.testserver/pull/44

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.22*

## ❌️ General: 98%

<details><summary>8 out of 528 features are not covered by tests</summary><p>

[`additionalPropertiesInProperties`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInProperties), [`additionalPropertiesInPropertiesWithAPTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInPropertiesWithAPTypeString), [`additionalPropertiesTrue`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTrue), [`additionalPropertiesTypeObject`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeObject), [`additionalPropertiesTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeString), [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putComplexPolymorphismNoDiscriminator`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismNoDiscriminator)</p></details>

## ✔️ Azure: 100%

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.22*

## ❌️ General: 98%

<details><summary>8 out of 528 features are not covered by tests</summary><p>

[`additionalPropertiesInProperties`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInProperties), [`additionalPropertiesInPropertiesWithAPTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInPropertiesWithAPTypeString), [`additionalPropertiesTrue`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTrue), [`additionalPropertiesTypeObject`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeObject), [`additionalPropertiesTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeString), [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putComplexPolymorphismNoDiscriminator`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismNoDiscriminator)</p></details>

## ✔️ Azure: 100%

**Comment by shahabhijeet** [comment]
@olydis @fearthecowboy any idea why those tests are only failing on the Linux box?

**Comment by fearthecowboy** [comment]
@shahabhijeet - Yes, @olydis  and I are aware of that; it's a behavior problem in the .net framework on linux (and IIRC, it's really just a testing problem; I'm pretty sure we don't encounter that in real-world use.) 

@olydis -- ?

**Comment by olydis** [comment]
@fearthecowboy no, the Linux failure is a real issue it's the `using` that disposes an `HttpRequestMessage` or something (don't recall the details), which in turn disposes the underlying `NetworkStream`. On windows, prefetching/buffering seems to consistently turn the entire (short) stream offline before the end of the using block. On linux this is not the case, so when the test case tries to read from the stream, there is no data and no more way to get it. This is actually a really hard problem, since either we can't dispose of the message at all (how would we know when the user is done with the stream?) or we create a stream wrapper that is able to dispose something else (like the message) on its own disposal... I drafted something like that in LinqPad, but it all sounds awful.

**Pull request merged**
