### PR TITLE
[LLC] Save Credentials in field for customization usage 

### LINKED ISSUE #1217: [LLC] Store credential and not just pipeline
Today the generated code for LLC creates a pipeline from the credential passed in and store it.

For some use cases, we need to access the credential later.

Should we store it off for use? If so what accessibility - public? protected? privatE?

### PR DESCRIPTION
**Pull request by chamons**
- Fixes #1217

### CODE REVIEW

**Comment by pakrym** [comment]
Can you show a customization that you have in mind?

**Comment by chamons** [comment]
The request came from @KrzysztofCwalina and was described as:

```
One of the grow-up methods needs access to the credential, but the generated ctors don't store the credential. They wrap the cred in a policy and add the policy to the pipeline. 
```

**Comment by pakrym** [comment]
I still don't understand what are we trying to do. Are we adding a new ctor? Then the ctor would have access to the credential (it would be a parameter).

**Comment by KrzysztofCwalina** [comment]
> I still don't understand what exactly are we trying to do. Are we adding a new ctor? Then the ctor would have access to the credential (it would be a parameter).

The client has a handcrafted method that needs access to credentials passed to the [generated] constructor.

**Review by pakrym — APPROVED** [review]

**Comment by pakrym** [comment]
@KrzysztofCwalina thank you for the example. Now I understand. I have rarely seen a client that needs access to the credential outside of the auth policy.

**Pull request merged**
