### PR TITLE
Take model kind into account when generating properties and serialization

### PR DESCRIPTION
**Pull request by pakrym**
Fixes: https://github.com/Azure/autorest.csharp/issues/529

### CODE REVIEW

**Comment by pakrym** [comment]
cc @heaths related to what you are doing

**Comment by heaths** [comment]
Adding myself as a reviewer so I can view in Code. GH PRs don't handle large PRs well.

**Comment by pakrym** [comment]
> I'm hoping read-only'ness will be as easy.

It won't :) The serialization code depends on type being mutable but I'm working on making serializer changes that would make it easier.

**Comment by heaths** [comment]
Ideally, if we have a "property bag" of those attributes we can pass down it would be easier. I just haven't had time to go back to it since I've been wrestling to just get the models I have now out.

**Pull request merged**
