### PR TITLE
[LLC] Make `requestBody` last required parameter

### PR DESCRIPTION
**Pull request by ellismg**
Upon using the generator for some services that have operations with
both a body and required path parameters, we noticed that having the
body parameter come first in the parameter list ends up feeling weird
when there are other required parameters.

Move the body paramter to the end of the required parameter list so
the generated code is more plesent to use.

### CODE REVIEW

**Comment by ellismg** [comment]
Not sure what the right thing to do for testing his here, @chamons.  If we had samples based on the purview stuff, we would have seen diffs when we re-ran `.\eng\Generate.ps1`, but currently the samples we use for LLC don't have a pattern of both a required path and body parameter.

Should I try to find something in the test server swaggers that looks like it might have the shape I want and then include that in the set of swaggers we use in `.\eng\Generate.ps1`?  Some other strategy here?

**Comment by chamons** [comment]
This is blocked by https://github.com/Azure/autorest.csharp/pull/1139

**Comment by chamons** [comment]
@ellismg - If you can find an existing swagger (either under test/TestProjects or in autorest.testserver) then we can add it to the generate.ps1 section for double generation into LLC and write a client test.

If not, it would make sense to create a new swagger under TestProjects.

**Review by chamons — APPROVED** [review]
Merge latest feature/v3 and see what tests need updating (if any).

Change LGTM.

**Comment by chamons** [comment]
@ellismg  - I think this can land.

**Pull request merged**
