### PR TITLE
[LLC] Add Documentaion for Input Scheama Shapes

### PR DESCRIPTION
**Pull request by ellismg**
This change adds logic to include a table in the `<remarks>` section
of a method documentation with information about about the input shape
of the method and gives information about the properties every object
has, if they are required or not, their types, and a description.

### CODE REVIEW

**Review by chamons — APPROVED** [review]
I would ask for tests, but asking "do the comments exist" is kinda hard. 

Thoughts on ^ @pakrym

**Comment by chamons** [comment]
Looks like you need to run ./eng/Generate.ps1 for the entire repository.

**Comment by ellismg** [comment]
> I would ask for tests, but asking "do the comments exist" is kinda hard.

I can write unit tests for the schema -> doc info stuff if that's helpful.  We do have some coverage via our samples, so we can at least get some notification when the comment shapes change and understand if that was "right" or not.

**Comment by chamons** [comment]
I'm personally fine w\ a "just eyeball comment changes in the checked in tests/sample" here, but I want Pavel's opinion if possible.

**Comment by chamons** [comment]
@ellismg - I think you can land this when ready.

**Pull request merged**
