### PR TITLE
fix(dpg): incorrect enum convenience/protocol parameter conversion

### LINKED ISSUE #3881: Generated code using an enum of ints does not compile
In Event Grid V2, an enum of ints is defined here - https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventgrid/Azure.Messaging.EventGrid/main.tsp#L129-L144

This gets generated as a struct with a few well known values.

The convenience method that is generated using the generated `ReleaseDelay` model. The method calls into the protocol method which defines the delay as an int, but it doesn't use the generated `ToSerialInt32` method so the code fails to compile.

### PR DESCRIPTION
**Pull request by archerzz**
# Description

- add missing logic to convert method parameter of int/float enum types from convenience to protocol
- add temporary test case

fix #3881

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

### CODE REVIEW

**Comment by archerzz** [comment]
We need to add some test cases in `cadl-ranch` later: https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/type/enum

**Review by chunyu3 — APPROVED** [review]

**Comment by chunyu3** [comment]
Please add tests in cadl-ranch.

**Review by JoshLove-msft — APPROVED** [review]

**Comment by archerzz** [comment]
Regen Preview: https://github.com/Azure/azure-sdk-for-net/pull/39720

No actual change

**Comment by JoshLove-msft** [comment]
Can this be merged?

**Review by ArthurMa1978 — APPROVED** [review]

**Comment by archerzz** [comment]
blocked by https://github.com/Azure/autorest.csharp/pull/3917

**Review by lirenhe — APPROVED** [review]

**Comment by archerzz** [comment]
@JoshLove-msft This PR has been merged. It should unblock your work on the enum parameters.

**Pull request merged**
