### PR TITLE
Align the constant schema behavior for mgmt (models and operations) and HLC (models and some cases in operations)

### PR DESCRIPTION
**Pull request by ArcturusZhang**
First step of https://github.com/Azure/autorest.csharp/issues/3230

# Description

This PR applies the first piece of the decision in [this comment](https://github.com/Azure/autorest.csharp/issues/3230#issuecomment-1486340259)

For HLC part, this PR only covers the model property part and partially covers the operation part, because HLC is generating clients and operations by converting the codemodel into input types. The missing part in HLC will be covered when we fix DPG.

**Legend**: ✅case fixed in this PR or correct previously, ❌ case not fixed by this PR and incorrect previously (will fix in other PRs)
| combination | mgmt | hlc | dpg | proposal |
| :-- | :-- | :-- | :-- | :-- |
| required string/int/float constant in model property | ✅ | ✅ | ❌ | public<br>extensible enum<br>initializer in ctor<br>no setter<br>include in serialization<br>include in deserialization |
| optional string/int/float constant in model property | ✅ | ✅ | ❌ | public<br>extensible enum: always<br>no initializer<br>setter<br>include in serialization<br>include in deserialization |
| required string/int/float constant in method parameter | ✅ | ✅ | ✅ | not show up in the method<br>hardcode in request<br>no extensible enum |
| optional string/int/float constant in method parameter | ✅ | ❌ | ❌ | show up in the method as optional<br>extensible enum: always<br>should not hardcode in request |
| required boolean constant in model property | ✅ | ✅ | ❌ | public<br>initializer in ctor<br>no setter<br>include in serialization<br>include in deserialization |
| optional boolean constant in model property | ✅ | ✅ | ❌ | public<br>no initializer<br>setter<br>include in serialization<br>include in deserialization |
| required boolean constant in method parameter | ✅ | ✅ | ✅ | not show up in the method<br>hardcode in request<br>no extensible enum |
| optional boolean constant in method parameter | ✅ | ❌ | ❌ | show up in the method as optional<br>should not hardcode in request |

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Hi @m-nash could you have a review on this?

**Comment by ArcturusZhang** [comment]
@m-nash could you please have a review?

**Comment by ArcturusZhang** [comment]
> @m-nash could you please have a review?

Latest regen: https://github.com/Azure/azure-sdk-for-net/pull/35596

**Comment by m-nash** [comment]
@ArcturusZhang can we take a stab at fixing all the [back compat issues](https://github.com/Azure/azure-sdk-for-net/pull/35596/files#diff-58ce175fd6e5f9b9089d612a2cd89771f4bb365d4c68df13dda6aef2be962438L37-R37) so we can see what those end up like?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang can we take a stab at fixing all the [back compat issues](https://github.com/Azure/azure-sdk-for-net/pull/35596/files#diff-58ce175fd6e5f9b9089d612a2cd89771f4bb365d4c68df13dda6aef2be962438L37-R37) so we can see what those end up like?

sure I will get a new regen PR and do it there

**Comment by ArcturusZhang** [comment]
Hi @m-nash I have mitigated any breaking changes in the regen: https://github.com/Azure/azure-sdk-for-net/pull/35718
Now the pipelines in the regen could pass properly.

**Comment by m-nash** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/35718#discussion_r1176816474

**Comment by ArcturusZhang** [comment]
Hi @m-nash could you please take a look at this new regen PR? https://github.com/Azure/azure-sdk-for-net/pull/36084
I managed to resolve all the breaking changes and now we have zero behavioral changes.
I did not change any of the test cases, and now they all passed.

**Comment by m-nash** [comment]
@ArcturusZhang left some comments on the regen https://github.com/Azure/azure-sdk-for-net/pull/36084#pullrequestreview-1420740381

**Review by m-nash — APPROVED** [review]

**Pull request merged**
