### PR TITLE
Draft of the document on "How to mock extension method in mgmt SDKs"

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Related issue: https://github.com/Azure/autorest.csharp/issues/3493

# Description
<i>Add your description here!</i>

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
@m-nash @KrzysztofCwalina @tg-msft could you also have a review on this to see if anything is missing in this doc?

Related implementations: https://github.com/Azure/autorest.csharp/pull/3483
https://github.com/Azure/azure-sdk-for-net/pull/37927

**Comment by scottaddie** [comment]
@ArcturusZhang Let's hold off on merging this PR. The content is better suited for learn.microsoft.com.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang Let's hold off on merging this PR. The content is better suited for learn.microsoft.com.

Yes we are not targeting to merge this, just use this PR to collect feedbacks and comments
Also we will release a few beta versions for some libraries and the testers might need a document, this is also for that purpose too

**Comment by ArcturusZhang** [comment]
I also added a section for `NSubstitute`

**Pull request closed without merging**
