### PR TITLE
Fix arm resource extension

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Fixes https://github.com/Azure/autorest.csharp/issues/2790
<del>Depends on https://github.com/Azure/autorest.csharp/pull/3257</del>

# Description

We previously have a bug that all scope method (the methods that are not detected to be on a resource) will not be generated, for instance `/{scope}/providers/Microsoft.Monitor/doSomething`

This PR fixes this issue, and methods like this will be generated as extension methods following the same pattern as ArmResourceExtensions, like
```csharp
public partial static class RPExtensions
{
// this method will always be generated
public static Response<DoSomethingResult> DoSomething(this ArmClient client, ResourceIdentifier scope, /* other parameters if any */ CancellationToken cancellationToken = default)
{
}

// this method is only generated when we have the corresponding entries in the `generate-arm-resource-extensions` configuration
public static Response<DoSomethingResult> DoSomething(this ArmResource armResource, /* other parameters if any */ CancellationToken cancellationToken = default)
{
}
}
```

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
@m-nash @ArthurMa1978 could you take a look?

**Review by m-nash — APPROVED** [review]
Approving as long as the answer to this question is true.

Are all the diffs in the regen preview that added new APIs things that were missing due to the bug that is linked?  Meaning they are extensions on non resources?

**Comment by ArcturusZhang** [comment]
> 

Yes.

**Comment by ArcturusZhang** [comment]
> Approving as long as the answer to this question is true.
> 
> Are all the diffs in the regen preview that added new APIs things that were missing due to the bug that is linked? Meaning they are extensions on non resources?

Yes. We will polish all the new apis introduced by this change and then merge this PR

**Review by ArthurMa1978 — APPROVED** [review]

**Pull request merged**
