### PR TITLE
Generate managers and POMs for Azure SDK for Java

### PR DESCRIPTION
**Pull request by olydis**
replay of Azure/autorest#2467

### CODE REVIEW

**Comment by olydis** [comment]
# publish job
~~~ Haskell
> waiting for PR to get merged or closed
~~~

**Comment by olydis** [comment]
# publish job
~~~ Haskell
> waiting for PR to get merged or closed
~~~

**Comment by olydis** [comment]
@RikkiGibson oh no that's just our new publish job notifying you that it'll publish one this gets merged. The publish job is polling based so if you open a PR and merge it within 10s, chances are, the publish job hasn't even noticed the PR before it's already gone again... so this message indicates that the PR has been acknowledged.

On the other hand, what *is* the plan with this PR? :D

**Comment by RikkiGibson** [comment]
I think the plan is to recreate with a new head branch. I have some housekeeping to do related to C#.

**Comment by olydis** [comment]
# AutoRest automatic publish job
~~~ Haskell
> will publish once/if PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Pull request closed without merging**
