### PR TITLE
remvoe resource operation

### PR DESCRIPTION
**Pull request by chunyu3**
# Description
Fix https://github.com/Azure/autorest.csharp/issues/2943
Fix https://github.com/Azure/autorest.csharp/issues/3877
- remove the wrapper to use resourceOperation type as input/output model

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

### CODE REVIEW

**Review by pshao25 — APPROVED** [review]
Do we need tests?

**Review by lirenhe — COMMENTED** [review]
As you are fixing 2 bugs, could you add some test cases to verify those 2 issues are resolved?  thanks

**Comment by chunyu3** [comment]
> As you are fixing 2 bugs, could you add some test cases to verify those 2 issues are resolved? thanks

I will add test case in cadl-ranch.

**Review by lirenhe — APPROVED** [review]

**Comment by lirenhe** [comment]
> > As you are fixing 2 bugs, could you add some test cases to verify those 2 issues are resolved? thanks
> 
> I will add test case in cadl-ranch.

Thanks.  Approved this PR.

**Pull request merged**
