### PR TITLE
Rename nuget package to Microsoft.Azure.AutoRest.CSharp and swap to single feed

### PR DESCRIPTION
**Pull request by chamons**
- Fixes https://github.com/Azure/autorest.csharp/issues/991
- Tested by applying https://gist.github.com/chamons/47c56587b62a114ce364e08070c83d43 to azure-sdk-for-net and building one synapse lib with a local nuget feed

### CODE REVIEW

**Review by pakrym — APPROVED** [review]

**Comment by pakrym** [comment]
https://github.com/Azure/autorest.csharp/pull/994 would need to go in first. We've updated some shared sources in Azure.Core.

**Comment by chamons** [comment]
Looks like that went it, this ready now @pakrym ?

**Comment by pakrym** [comment]
Let's hold this off until I can get the https://github.com/Azure/azure-sdk-for-net/pull/18022 merged. It has a few manual changes that would be overwritten by automation and customers have been waiting for it for a while.

**Comment by chamons** [comment]
Cool - just poke me when you want me to move forward (or just slap merge yourself).

**Comment by pakrym** [comment]
Will do, should be pretty soon.

**Comment by chamons** [comment]
@pakrym and I discussed on teams, ready to land.

**Comment by aelij** [comment]
@chamons The new package doesn't appear on nuget.org, is that intentional? I see `AutoRest.CSharp` but it's unlisted.

**Pull request merged**
