### PR TITLE
Switch Publishing to DevOps Feed

### PR DESCRIPTION
**Pull request by chidozieononiwu**
# Description
- Switch to publishing to the public `azure-sdk-for-net` https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net%40Local/nuget/v3/index.json DevOps feed.

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

### CODE REVIEW

**Comment by pakrym** [comment]
Do we consume it in azure-sdk-for-net?

**Review by chamons — APPROVED** [review]

**Comment by chamons** [comment]
👍  is conditional on a green build and Pavel's 👍

**Comment by chidozieononiwu** [comment]
> Do we consume it in azure-sdk-for-net?

Are you referring to the feed or autorest? Yes we do reference the feed in [Nuget.Config](https://github.com/Azure/azure-sdk-for-net/blob/4dfab56fea9eb98269dd202a87ce35f33bc4e226/NuGet.Config#L7)

**Review by pakrym — APPROVED** [review]

**Pull request merged**
